# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch
import numpy as np
tensor_1 = torch.rand(7,7)
tensor_1
# Create random tensor


tensor([[0.0388, 0.0062, 0.0444, 0.0266, 0.3591, 0.1012, 0.0721],
        [0.0602, 0.9563, 0.5156, 0.6104, 0.3822, 0.6953, 0.9051],
        [0.6804, 0.6731, 0.2202, 0.8590, 0.8486, 0.6262, 0.1026],
        [0.0221, 0.8604, 0.3362, 0.3943, 0.0858, 0.1412, 0.7474],
        [0.2866, 0.4802, 0.3753, 0.1470, 0.1238, 0.0091, 0.9755],
        [0.0514, 0.1680, 0.9953, 0.7528, 0.1340, 0.4949, 0.6238],
        [0.7896, 0.3652, 0.0846, 0.9504, 0.0563, 0.4536, 0.6449]])

In [9]:
type(tensor_1)

torch.Tensor

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [14]:
# Create another random tensor
tensor_2 = torch.rand(size=(1,7))
tensor_2
# Perform matrix multiplication
torch.matmul(tensor_1,tensor_2.T), torch.matmul(tensor_1,tensor_2.T).shape

(tensor([[0.3173],
         [1.4513],
         [1.7131],
         [0.9033],
         [1.1889],
         [1.2122],
         [1.6589]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [20]:
# Set manual seed
torch.seed=0
tensor_1 = torch.rand(7,7)
torch.seed = 0
tensor_2 = torch.rand(size=(1,7))
print(tensor_1,tensor_2)

torch.matmul(tensor_1,tensor_2.T)

# Create two random tensors


# Matrix multiply tensors


tensor([[0.4331, 0.3617, 0.5405, 0.9710, 0.1521, 0.0771, 0.5113],
        [0.6433, 0.4427, 0.4831, 0.5335, 0.1631, 0.6401, 0.7806],
        [0.8988, 0.4633, 0.0427, 0.8629, 0.3481, 0.5513, 0.0203],
        [0.4895, 0.1713, 0.5180, 0.1562, 0.2717, 0.4934, 0.3226],
        [0.7280, 0.1899, 0.8105, 0.2510, 0.7688, 0.2082, 0.9914],
        [0.4713, 0.8064, 0.2785, 0.7971, 0.1592, 0.4963, 0.4586],
        [0.0553, 0.2116, 0.1198, 0.4855, 0.2909, 0.7934, 0.9069]]) tensor([[0.8247, 0.7685, 0.3995, 0.6089, 0.4147, 0.5788, 0.3438]])


tensor([[1.7259],
        [2.0951],
        [2.1102],
        [1.3465],
        [2.0032],
        [2.1160],
        [1.4434]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [21]:
# Set random seed on the GPU
torch.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [37]:
# Set random seed
torch.manual_seed(1234)
tensor_3 = torch.rand(size=(2,3))
tensor_4 = torch.rand(size=(2,3))
# Check for access to GPU

# Create two random tensors on GPU

device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
tensor_3_gpu = tensor_3.to(device)
tensor_4_gpu= tensor_4.to(device)

tensor_3_gpu,tensor_4_gpu

cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [39]:
# Perform matmul on tensor_A and tensor_B

tensor5=torch.matmul(tensor_3_gpu ,tensor_4_gpu.reshape(3,2))
tensor5

tensor([[0.4759, 0.2931],
        [0.6074, 0.5855]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [43]:
# Find max
torch.max(tensor5), torch.min(tensor5)
# Find min


(tensor(0.6074, device='cuda:0'), tensor(0.2931, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [44]:
# Find arg max
torch.argmax(tensor5), torch.argmin(tensor5)

# Find arg min


(tensor(2, device='cuda:0'), tensor(1, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [48]:
# Set seed

seed = torch.manual_seed(7)

# Create random tensor
tensor_A = torch.rand(size=(1,1,1,10))
print(tensor_A, tensor_A.shape)

# Remove single dimensions

tensor_A_1=torch.squeeze(tensor_A)
print(tensor_A_1,tensor_A_1.shape)
# Print out tensors and their shapes


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
